#!/bin/bash

#############################################################

# This script will list all the resources in the AWS Account
# Author : Abhishek /Devops Team
# Version :v0.0.1
# Following are the services suported by the script
#1 VPC
#2 S3
#3 Lambda
#3 EBS

#usage : ./aws_resource_list.sh <Region> <Service_name>
#Example : ./aws_resources_list.sh us-east-1 EC2

###############################################################

#check if the number of arguments are two , and are passed.

if [ $# -ne 2 ]; then
      echo "usage: $0 <region> <service>"
      exit 1
fi

# Assign arguments to the variables and convert them to lowercase 

aws_region=$1
aws_service=$2

# check if the AWS is configured or not

if [ ! -d ~/.aws ]; then
    echo "AWS CLI is configured on the machine"
    exit 1
fi

# check if the AWS CLI is installed or not

if ! command -v aws &> /dev/null; then
    echo "AWS CLI is not installed.Please install it and try again".
    exit 1
fi
###############################
# List the resourcs based on the service 

case $aws_service in 
ec2)
echo "listing ec2 instances in $aws_region"
aws ec2 describe-instances --region $aws_region 
;;
s3)
echo "Listing the s3 buckets in aws $aws_region"
aws s3api list-buckets --region $aws_region
;;
vpc)
echo "Listing all the VPC present $aws_region"
aws ec2 describe-vpcs --region $aws_region
;;
esac





